// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --local > src/lib/database.types.ts
// For now, we'll use a minimal type definition

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      words: {
        Row: {
          id: string
          word: string
          created_at: string
        }
        Insert: {
          id?: string
          word: string
          created_at?: string
        }
        Update: {
          id?: string
          word?: string
          created_at?: string
        }
      }
      flashcards: {
        Row: {
          id: string
          user_id: string
          front: string
          back: string | null
          language: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id?: string
          front: string
          back?: string | null
          language?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          front?: string
          back?: string | null
          language?: string
          updated_at?: string
        }
      }
      decks: {
        Row: {
          id: string
          user_id: string
          name: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id?: string
          name: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          updated_at?: string
        }
      }
      deck_flashcards: {
        Row: {
          id: string
          deck_id: string
          flashcard_id: string
          position: number
          added_at: string
        }
        Insert: {
          id?: string
          deck_id: string
          flashcard_id: string
          position?: number
          added_at?: string
        }
        Update: {
          position?: number
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
